HealthDesign/urls.py
from django.conf.urls import url
from . import views

app_name = 'HealthDesign'

urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^(?P<demographics_id>[0-9]+)/$', views.detail, name='detail'),

    # HealthDesign/add-demographics/
    url(r'add-demographics/$', views.demographics_create, name='demographics-add'),

    # HealthDesign/3/update-demographics/
    url(r'(?P<demographics_id>[0-9]+)/update-demographics/$', views.demographics_update, name='demographics-update'),

    # HealthDesign/3/delete-demographics/
    url(r'(?P<demographics_id>[0-9]+)/delete-demographics/$', views.demographics_delete, name='demographics-delete'),

    # HealthDesign/2/add-guardian/
    url(r'(?P<demographics_id>[0-9]+)/add-guardian/$', views.guardian_create, name='guardian-add'),

    # HealthDesign/2/3/update-guardian/
    url(r'(?P<demographics_id>[0-9]+)/(?P<guardian_id>[0-9]+)/update-guardian/$', views.guardian_update, name='guardian-update'),

    # HealthDesign/3/2/delete-guardian/
    url(r'(?P<demographics_id>[0-9]+)/(?P<guardian_id>[0-9]+)/delete-guardian/$', views.guardian_delete, name='guardian-delete'),

    # HealthDesign/2/add-provider/
    url(r'(?P<demographics_id>[0-9]+)/add-provider/$', views.provider_create, name='provider-add'),

    # HealthDesign/2/1/update-provider/
    url(r'(?P<demographics_id>[0-9]+)/(?P<provider_id>[0-9]+)/update-provider/$', views.provider_update, name='provider-update'),

    # HealthDesign/3/2/delete-provider/
    url(r'(?P<demographics_id>[0-9]+)/(?P<provider_id>[0-9]+)/delete-provider/$', views.provider_delete, name='provider-delete'),

    # HealthDesign/2/add-allergies/
    url(r'(?P<demographics_id>[0-9]+)/add-allergies/$', views.allergies_create, name='allergies-add'),

    # HealthDesign/2/1/update-allergies/
    url(r'(?P<demographics_id>[0-9]+)/(?P<allergies_id>[0-9]+)/update-allergies/$', views.allergies_update, name='allergies-update'),

    # HealthDesign/3/2/delete-allergies/
    url(r'(?P<demographics_id>[0-9]+)/(?P<allergies_id>[0-9]+)/delete-allergies/$', views.allergies_delete, name='allergies-delete'),

    # HealthDesign/2/add-immunizations/
    url(r'(?P<demographics_id>[0-9]+)/add-immunizations/$', views.immunizations_create, name='immunizations-add'),

    # HealthDesign/2/4/update-immunizations/
    url(r'(?P<demographics_id>[0-9]+)/(?P<immunizations_id>[0-9]+)/update-immunizations/$', views.immunizations_update, name='immunizations-update'),

    # HealthDesign/3/2/delete-immunizations/
    url(r'(?P<demographics_id>[0-9]+)/(?P<immunizations_id>[0-9]+)/delete-immunizations/$', views.immunizations_delete, name='immunizations-delete'),

    # HealthDesign/2/add-medication/
    url(r'(?P<demographics_id>[0-9]+)/add-medication/$', views.medication_create, name='medication-add'),

    # HealthDesign/2/5/update-medication/
    url(r'(?P<demographics_id>[0-9]+)/(?P<medication_id>[0-9]+)/update-medication/$', views.medication_update, name='medication-update'),

    # HealthDesign/3/2/delete-medication/
    url(r'(?P<demographics_id>[0-9]+)/(?P<medication_id>[0-9]+)/delete-medication/$', views.medication_delete, name='medication-delete'),

    # HealthDesign/2/add-careplan/
    url(r'(?P<demographics_id>[0-9]+)/add-careplan/$', views.careplan_create, name='careplan-add'),

    # HealthDesign/2/6/update-careplan/
    url(r'(?P<demographics_id>[0-9]+)/(?P<careplan_id>[0-9]+)/update-careplan/$', views.careplan_update, name='careplan-update'),

    # HealthDesign/3/2/delete-careplan/
    url(r'(?P<demographics_id>[0-9]+)/(?P<careplan_id>[0-9]+)/delete-careplan/$', views.careplan_delete, name='careplan-delete'),

    # HealthDesign/2/add-encounters/
    url(r'(?P<demographics_id>[0-9]+)/add-encounters/$', views.encounters_create, name='encounters-add'),

    # HealthDesign/2/1/update-encounters/
    url(r'(?P<demographics_id>[0-9]+)/(?P<encounters_id>[0-9]+)/update-encounters/$', views.encounters_update, name='encounters-update'),

    # HealthDesign/3/2/delete-encounters/
    url(r'(?P<demographics_id>[0-9]+)/(?P<encounters_id>[0-9]+)/delete-encounters/$', views.encounters_delete, name='encounters-delete'),

    # HealthDesign/2/add-problemlist/
    url(r'(?P<demographics_id>[0-9]+)/add-problemlist/$', views.problemlist_create, name='problemlist-add'),

    # HealthDesign/2/2/update-problemlist/
    url(r'(?P<demographics_id>[0-9]+)/(?P<problemlist_id>[0-9]+)/update-problemlist/$', views.problemlist_update, name='problemlist-update'),

    # HealthDesign/3/2/delete-problemlist/
    url(r'(?P<demographics_id>[0-9]+)/(?P<problemlist_id>[0-9]+)/delete-problemlist/$', views.problemlist_delete, name='problemlist-delete'),

    # HealthDesign/2/add-procedures/
    url(r'(?P<demographics_id>[0-9]+)/add-procedures/$', views.procedures_create, name='procedures-add'),

    # HealthDesign/2/1/update-procedures/
    url(r'(?P<demographics_id>[0-9]+)/(?P<procedures_id>[0-9]+)/update-procedures/$', views.procedures_update, name='procedures-update'),

    # HealthDesign/3/2/delete-procedures/
    url(r'(?P<demographics_id>[0-9]+)/(?P<procedures_id>[0-9]+)/delete-procedures/$', views.procedures_delete, name='procedures-delete')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('HealthDesign.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthDesign/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Demographics, Guardian, Provider, Allergies, Immunizations, Medication, ProblemList, CarePlan, Encounters, Procedures


class DemographicsForm(forms.ModelForm):
    class Meta:
        model = Demographics
        fields = ['first_name', 'last_name', 'gender', 'martial_status', 'religious_affiliation',
                  'ethnicity',
                  'language_spoken',
                  'address',
                  'telephone',
                  'birthday'
                  ]


class GuardianForm(forms.ModelForm):
    class Meta:
        model = Guardian
        fields = ['first_name', 'last_name', 'role', 'address', 'telephone']


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = ['name', 'address', 'telephone' ]

class AllergiesForm(forms.ModelForm):
    class Meta:
        model = Allergies
        fields = ['allergy_name', 'reaction', 'severity']


class ImmunizationsForm(forms.ModelForm):
    class Meta:
        model = Immunizations
        fields = ['date', 'immunizations_name', 'type', 'dose_quantity', 'instructions']

class MedicationForm(forms.ModelForm):
    class Meta:
        model = Medication
        fields = ['date', 'type', 'medication_name', 'instructions', 'dose_quantity', 'rate_quantity', 'prescriber_name']

class CarePlanForm(forms.ModelForm):
    class Meta:
        model = CarePlan
        fields = ['name', 'date', 'instructions']

class EncountersForm(forms.ModelForm):
    class Meta:
        model = Encounters
        fields = ['encounter', 'provider', 'location', 'date']

class ProblemListForm(forms.ModelForm):
    class Meta:
        model = ProblemList
        fields = ['observation', 'status', 'date', 'comment']


class ProceduresForm(forms.ModelForm):
    class Meta:
        model = Procedures
        fields = ['procedure', 'date', 'provider', 'location']

HealthDesign/views.py
from django.shortcuts import render, get_object_or_404
from .forms import DemographicsForm, GuardianForm, ProviderForm, ImmunizationsForm, CarePlanForm, ProblemListForm, ProceduresForm, AllergiesForm, MedicationForm, EncountersForm
from .models import Demographics, Guardian, Provider, Immunizations, CarePlan, Encounters,Allergies,Medication, Procedures, ProblemList
from django.db.models import Q


def index(request):
    demographics_list = Demographics.objects.all()
    query = request.GET.get("q")
    if query:
        demographics_list = demographics_list.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query)
        ).distinct()
    return render(request, 'HealthDesign/index.html', {'demographics_list': demographics_list})


def detail(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    return render(request, 'HealthDesign/detail.html', {'demographics': demographics})

def demographics_create(request):
    form = DemographicsForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        demographics = form.save(commit=False)
        demographics.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
    }
    return render(request, 'HealthDesign/demographics_form.html', context)

def demographics_update(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    form = DemographicsForm(request.POST or None, request.FILES or None, instance=demographics)
    if form.is_valid():
        demographics = form.save(commit=False)
        demographics.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
    }
    return render(request, 'HealthDesign/demographics_form.html', context)

def demographics_delete(request, demographics_id):
    get_object_or_404(Demographics, pk=demographics_id).delete()
    demographics_list = Demographics.objects.all()
    return render(request, 'HealthDesign/index.html', {'demographics_list': demographics_list})

def guardian_create(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    form = GuardianForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        guardian = form.save(commit=False)
        guardian.demographics = demographics
        guardian.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/guardian_form.html', context)

def guardian_update(request, demographics_id, guardian_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    guardian = get_object_or_404(Guardian, pk=guardian_id)
    form = GuardianForm(request.POST or None, request.FILES or None, instance=guardian)
    if form.is_valid():
        guardian = form.save(commit=False)
        guardian.demographics = demographics
        guardian.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/guardian_form.html', context)

def guardian_delete(request, demographics_id, guardian_id):
    get_object_or_404(Guardian, pk=guardian_id).delete()
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    return render(request, 'HealthDesign/detail.html', {'demographics': demographics})

def provider_create(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    form = ProviderForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        provider = form.save(commit=False)
        provider.demographics = demographics
        provider.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/provider_form.html', context)

def provider_update(request, demographics_id, provider_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    provider = get_object_or_404(Provider, pk=provider_id)
    form = ProviderForm(request.POST or None, request.FILES or None, instance=provider)
    if form.is_valid():
        provider = form.save(commit=False)
        provider.demographics = demographics
        provider.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/provider_form.html', context)

def provider_delete(request, demographics_id, provider_id):
    get_object_or_404(Provider, pk=provider_id).delete()
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    return render(request, 'HealthDesign/detail.html', {'demographics': demographics})

def allergies_create(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    form = AllergiesForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        allergy = form.save(commit=False)
        allergy.demographics = demographics
        allergy.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/allergies_form.html', context)

def allergies_update(request, demographics_id, allergies_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    allergy = get_object_or_404(Allergies, pk=allergies_id)
    form = AllergiesForm(request.POST or None, request.FILES or None, instance=allergy)
    if form.is_valid():
        allergy = form.save(commit=False)
        allergy.demographics = demographics
        allergy.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/allergies_form.html', context)

def allergies_delete(request, demographics_id, allergies_id):
    get_object_or_404(Allergies, pk=allergies_id).delete()
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    return render(request, 'HealthDesign/detail.html', {'demographics': demographics})

def immunizations_create(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    form = ImmunizationsForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        immunization = form.save(commit=False)
        immunization.demographics = demographics
        immunization.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/immunizations_form.html', context)

def immunizations_update(request, demographics_id, immunizations_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    immunization = get_object_or_404(Immunizations, pk=immunizations_id)
    form = ImmunizationsForm(request.POST or None, request.FILES or None, instance=immunization)
    if form.is_valid():
        immunization = form.save(commit=False)
        immunization.demographics = demographics
        immunization.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/immunizations_form.html', context)

def immunizations_delete(request, demographics_id, immunizations_id):
    get_object_or_404(Immunizations, pk=immunizations_id).delete()
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    return render(request, 'HealthDesign/detail.html', {'demographics': demographics})

def medication_create(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    form = MedicationForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        medication = form.save(commit=False)
        medication.demographics = demographics
        medication.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/medication_form.html', context)

def medication_update(request, demographics_id, medication_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    medication = get_object_or_404(Medication, pk=medication_id)
    form = MedicationForm(request.POST or None, request.FILES or None, instance=medication)
    if form.is_valid():
        medication = form.save(commit=False)
        medication.demographics = demographics
        medication.save()
        return render(request, 'HealthDesign/detail.html', {'demographics': demographics})
    context = {
        "form": form,
        "demographics": demographics
    }
    return render(request, 'HealthDesign/medication_form.html', context)

def medication_delete(request, demographics_id, medication_id):
    get_object_or_404(Medication, pk=medication_id).delete()
    demographics = get_object_or_404(Demographics, pk=demographics_id)
    return render(request, 'HealthDesign/detail.html', {'demographics': demographics})

def careplan_create(request, demographics_id):
    demographics = get_object_or_404(Demographics, pk=demographics_id)

HealthDesign/templates/HealthDesign/allergies_form.html
{% extends 'HealthDesign/base.html' %}
{% block title %}Allergy{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ demographics.first_name }} {{ demographics.Last_name }}</h3>
                    <h5> Gender : {{ demographics.gender }}</h5>
                    <h5> Martial Status : {{ demographics.martial_status }}</h5>
                    <h5> Religious Affiliation : {{ demographics.religious_affiliation }}</h5>
                    <h5> Ethnicity : {{ demographics.ethnicity }}</h5>
                    <h5> Language Spoken : {{ demographics.language_spoken }}</h5>
                    <h5> Address : {{ demographics.address }}</h5>
                    <h5> Telephone : {{ demographics.telephone }}</h5>
                    <h5> Birthday : {{ demographics.birthday }}</h5>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Allergy</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="demographics_id" value="{{ demographics.id }}">
                        {% include 'HealthDesign/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

HealthDesign/templates/HealthDesign/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}HealthDesign{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'HealthDesign/style.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'HealthDesign:index' %}">Health Design</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="{% url 'HealthDesign:demographics-add'%}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'HealthDesign:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

HealthDesign/templates/HealthDesign/careplan_form.html
{% extends 'HealthDesign/base.html' %}
{% block title %}Care Plan{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ demographics.first_name }} {{ demographics.Last_name }}</h3>
                    <h5> Gender : {{ demographics.gender }}</h5>
                    <h5> Martial Status : {{ demographics.martial_status }}</h5>
                    <h5> Religious Affiliation : {{ demographics.religious_affiliation }}</h5>
                    <h5> Ethnicity : {{ demographics.ethnicity }}</h5>
                    <h5> Language Spoken : {{ demographics.language_spoken }}</h5>
                    <h5> Address : {{ demographics.address }}</h5>
                    <h5> Telephone : {{ demographics.telephone }}</h5>
                    <h5> Birthday : {{ demographics.birthday }}</h5>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Care Plan</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="demographics_id" value="{{ demographics.id }}">
                        {% include 'HealthDesign/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

HealthDesign/templates/HealthDesign/demographics_form.html
{% extends 'HealthDesign/base.html' %}
{% block title %}Demographics{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Demographics</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'HealthDesign/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

HealthDesign/templates/HealthDesign/encounters_form.html
{% extends 'HealthDesign/base.html' %}
{% block title %}Encounter{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ demographics.first_name }} {{ demographics.Last_name }}</h3>
                    <h5> Gender : {{ demographics.gender }}</h5>
                    <h5> Martial Status : {{ demographics.martial_status }}</h5>
                    <h5> Religious Affiliation : {{ demographics.religious_affiliation }}</h5>
                    <h5> Ethnicity : {{ demographics.ethnicity }}</h5>
                    <h5> Language Spoken : {{ demographics.language_spoken }}</h5>
                    <h5> Address : {{ demographics.address }}</h5>
                    <h5> Telephone : {{ demographics.telephone }}</h5>
                    <h5> Birthday : {{ demographics.birthday }}</h5>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Encounter</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="demographics_id" value="{{ demographics.id }}">
                        {% include 'HealthDesign/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

HealthDesign/templates/HealthDesign/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

HealthDesign/templates/HealthDesign/guardian_form.html
{% extends 'HealthDesign/base.html' %}
{% block title %}Guardian{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>{{ demographics.first_name }} {{ demographics.Last_name }}</h3>
                    <h5> Gender : {{ demographics.gender }}</h5>
                    <h5> Martial Status : {{ demographics.martial_status }}</h5>
                    <h5> Religious Affiliation : {{ demographics.religious_affiliation }}</h5>
                    <h5> Ethnicity : {{ demographics.ethnicity }}</h5>
                    <h5> Language Spoken : {{ demographics.language_spoken }}</h5>
                    <h5> Address : {{ demographics.address }}</h5>
                    <h5> Telephone : {{ demographics.telephone }}</h5>
                    <h5> Birthday : {{ demographics.birthday }}</h5>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Guardian</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="demographics_id" value="{{ demographics.id }}">
                        {% include 'HealthDesign/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

HealthDesign/templates/HealthDesign/index.html
{% extends 'HealthDesign/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        {% if demographics_list %}
            {% for demographics in demographics_list %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <div class="caption">
                            <h4>{{ demographics.first_name }} {{ demographics.last_name }} </h4>
                            <h5>{{ demographics.telephone }}</h5>

                            <a href="{% url 'HealthDesign:detail' demographics.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            <a href="{% url 'HealthDesign:demographics-delete' demographics.id %}" class="btn btn-primary btn-sm" role="button">Delete</a>




                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'HealthDesign:demographics-add'%}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add
                    </button>
                </a>
            </div>
        {% endif %}
    </div>


</div>
{% endblock %}